plugins:
  blog_post_enabled:
    default: false
    client: true
  blog_post_allowed_groups:
    type: list
    default: "admins|moderators"
    client: true
  blog_post_allowed_categories:
    type: list
    client: true
